blank_issues_enabled: false

contact_links:
  - name: 薄荷输入法官网
    url: https://www.mintimate.cc/
    about: 快速初始化rime⚡，同时适配多个平台💻。

  - name: RIME 定制文档
    url: https://github.com/rime/home/wiki
    about: 这里有自定义 RIME 方案的全面教程。

  - name: 小狼毫（Weasel）文档
    url: https://github.com/rime/weasel/wiki
    about: 这里有定制 Weasel 样式和行为的指导。

  - name: 鼠须管（Squirrel）文档
    url: https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/鼠鬚管介面配置指南.md
    about: 这里有定制 Squirrel 样式和行为的参考资料。
